version: "3.8"
services:
  php-apache:
    build: bin/php-apache/
    restart: always
    volumes:
      - "${APP_DIR}:/var/www/html"
      - "${PHP_INI}:/usr/local/etc/php/php.ini"
      - "${APACHE_VHOSTS_DIR}:/etc/apache2/sites-enabled"
      - "${APACHE_LOG_DIR}:/var/log/apache2"
      - "${XDEBUG_LOG_DIR}:/var/log/xdebug"
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: remote_port=${XDEBUG_REMOTE_PORT} idekey=${XDEBUG_IDE_KEY}
    depends_on:
      - mariadb
    links:
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - /var/lib/mysql
      - ${FULL_ROOT_DIR}/config/mariadb/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  www:
    driver_opts:
      type: none
      device: ${FULL_ROOT_DIR}/www
      o: bind
